### PR TITLE
Timers: We should support PWM on two more pins for the 48 pin variant

### PR DESCRIPTION
**Pull request by egilkv**
Note that the nice little picture of the 48 pin variant pins also should be updated. No idea how that is done.

The little trick setting up the routing saves 24 bytes of code, so totally worth it.

### CODE REVIEW

**Comment by MCUdude** [comment]
Egil is back, awesome!

I will change the pinout pic to reflect the changes. I'll just test on some hardware first before I merge it, just to be sure.

Would you like to have a look at the `attachInterrupt` implementation? I've made a [small write-up here](https://github.com/arduino/ArduinoCore-megaavr/issues/56). Basically, it's memory hungry and not very optimized. I'm sure it could be implemented in a much more elegant way.

**Comment by MCUdude** [comment]
I can't get PWM to work on PB5 (digital pin 13).

Here's the test code I wrote to test all PWM pins.

``` c
uint8_t pwmPinArray[] = {12, 13, 14, 15, 16, 17, 18, 19, 38, 39};

void setup() {
  
  for(uint8_t i = 0; i < sizeof(pwmPinArray); i++)
    pinMode(pwmPinArray[i], OUTPUT);

}

void loop() {
  // increase
  for(uint8_t i = 0; i < 255; i++)
  {
    for(uint8_t j = 0; j < sizeof(pwmPinArray); j++)
      analogWrite(pwmPinArray[j], i);
    delay(30);
  }

  // decrease
  for(uint8_t i = 255; i > 0; i--)
  {
    for(uint8_t j = 0; j < sizeof(pwmPinArray); j++)
      analogWrite(pwmPinArray[j], i);
    delay(30);
  }
}
```

**Comment by MCUdude** [comment]
No, something else is wrong. The issue I wrote about above was caused by me adding a typo in the `digital_pin_to_timer` array. However there is still an issue with PB5 which causes `delay()` to last forever. `delay()` is derived from timer3, and I suspect that this PR is causing timer3 to not count millis/micros the way it should.

**Comment by egilkv** [comment]
Thanks for checking. I will test once more. Pin 13 is connected to TCB3 which is now also the millis timer, but I imagined the two functions could be combined. I did test TCB3 on pin 13 but maybe it was when the millis timer was on TCB0? Again, will retest and come back.

**Comment by MCUdude** [comment]
This PR doesn't really do anything with timer3, except defining digital pin 13/PB5 as a pin that's attached to timer3. I believe [this code](https://github.com/MCUdude/MegaCoreX/blob/db73134eb36c97040e30adb083f858aaecf5ed84/megaavr/cores/coreX-corefiles/wiring_analog.c#L172-L184) is causing the issue.

**Comment by egilkv** [comment]
I have now quickly read the data sheet, always a good idea. There is only one interrupt possible for these timers, and in 8 bit PWM mode the interrupt is when the compare value is reached. Which means that if nothing else, the exact time of the millis interrupt will change with the PWM value, which is obviously not good. Will revisit this, please hang on.

**Comment by egilkv** [comment]
One thing that struck me was that it might be better to use a timer A for millis, because it for instance has a separate OVF interrupt which should be independent of PWM compare register Again, will look at this more.

**Comment by MCUdude** [comment]
Theoretically, will this allow us to have a total of 10 PWM pins? Another good thing about using TCA0 is that all mega0/tiny0/tiny1's have this, so it should be even easier to add support for potential new and more primitive targets. Looking forward to seeing what you'll come up with!

BTW what is the possibility of changing the PWM speed?  ~1kHz PWM frequency is often not ideal because the audible noise it creates when driving motors, inductors, etc. It would be awesome if it was possible to change the PWM frequency either without messing up millis/micros/delay.

**Comment by egilkv** [comment]
Changing the PWM speed is definitely possible, with some limitations. Off the bat it would seem like 4, 8, 16, 32 and 64 kHz should be possible on many of the PWM pins.

**Comment by MCUdude** [comment]
> Changing the PWM speed is definitely possible, with some limitations. Off the bat it would seem like 4, 8, 16, 32 and 64 kHz should be possible on many of the PWM pins.

But wouldn't this be an issue if millis/micros/delay would be generated by TCA0. TCA0 is the timer that handles most PWM outputs.

**Comment by egilkv** [comment]
That is included in "some limitations". You cannot (easily) change the PWM frequency of the timer that is used for timing.

**Comment by MCUdude** [comment]
That is certainly a big drawback. I suggest we keep using timerb3 for millis/micros/delay, since higher PWM speed is a must.

Can you modify this PR to only add PWM to PB4? One more PWM pin _is_ one more PWM pin!

**Comment by egilkv** [comment]
My thoughts too. Although I would actually propose switching to TCB2, simply because we then get a more continuous list of PWM pins:  13,14,15,16,17,18,19,38,39

With this configuration, it should be possible to change the frequency for all available PWM pins. The easiest would be having a function to change them all at once.

**Comment by MCUdude** [comment]
> My thoughts too. Although I would actually propose switching to TCB2, simply because we then get a more continuous list of PWM pins: 13,14,15,16,17,18,19,38,39

Good idea. Let's use TCB2. Can you update this PR to reflect this? I'll do some testing again when I get home from work. 

It would be great it the PWM speed change function was added as a separate PR. Could you do that?

**Comment by MCUdude** [comment]
Can you update the "Number of PWM pins" field in the README too? Should be 9 instead of 8.

**Comment by egilkv** [comment]
I have now pretty completely rewritten and simplified timing stuff. So everything involving millis(), micros(), delay() is all new. The accuracy should now be much better, and the code is simplified a lot, meaning it also runs with a good deal less overhead. This also paves the way for independent setting of PWM frequency as a nice side effect.

One reflection is that it may perhaps be better to stay with TCB3 for timing after all, since there are assumptions (like in Tone) that this timer is reserved.

**Comment by MCUdude** [comment]
Wow, fantastic! I'm not able to test all this until later tonight. It is some quite significant changes indeed! How would this affect (accurate) timing when running the AVR at other and slower clocks (see list of compatible clocks in README)?

**Comment by egilkv** [comment]
It should be fine with no changes down to 2 MHz. By changing the prescaler to 1 (easy enough), if would be fine down to 1 MHz. For anything lower, there would have to be some simple modifications.

**Comment by MCUdude** [comment]
It does indeed work very well down to 2 MHz. However, at 1 MHz delay() causes the microcontroller to hang. And delayMicroseconds seems to be too fast. Since 1 MHz is the lowest frequency this core supports, could you tweak the code to work well when running at 1 MHz too?

Again, this is excellent work. I'm sure @facchinm would be interested in at least have the new millis/micros/delay implementation added to the official code as well. A typical blink sketch is now ~300 bytes smaller in size.

**Comment by MCUdude** [comment]
A comment about `analogWriteFrequency`. PWM frequency is highly dependent on the actual clock speed. `analogWriteFrequency(1)` will only result in a 1 kHz PWM frequency when the main clock is running at 16 MHz. Maybe we should call it `analogWritePrescaler` and add some text in the readme about what prescaler factor will result in which PWM frequency for the supported clokc frequencies? I think this will be more accurate.

**Comment by egilkv** [comment]
I must admit I never tried the lower clock speeds. I definitely think the PWM frequency should be as independent of the CPU clock as possible, so that it is around 1kHz regardless of CPU. (It may not be exact, but this I believe is quite typical for Arduinos anyway) I can submit a fix for that, as well as the 1MHz. I cannot test now, maybe you can?

**Comment by MCUdude** [comment]
> I cannot test now, maybe you can?

Sure, I can test now!

**Comment by egilkv** [comment]
Re. delayMicroseconds() I don't think what I did should influence it (but I could be wrong!) Could you please do the same test on the old code to see if it was also wrong before? You cannot use micros() to measure, because the old micros() was probably not very accurate.

**Comment by MCUdude** [comment]
I'll test delayMicroseconds afterwards.

We still have some PWM frequency related issue we need to figure out.
* An 8 MHz clock result in a PWM frequency of 488 Hz. `analogWriteFrequency(1)` doesn't affect the PWM frequency.
* A 4 MHz clock result in a PWM frequency of 977 Hz. `analogWriteFrequency(1)` set the frequency down to 244Hz.
* A 2 MHz clock result in a PWM frequency of 977 Hz. `analogWriteFrequency(1)` set the frequency down to 122Hz.
* A 1 MHz clock result in a PWM frequency of 2.60kHz. `analogWriteFrequency(1)` set the frequency down to 162Hz.

**Comment by MCUdude** [comment]
Here are the test results

| Clock  | //analogWriteFrequency(1); | analogWriteFrequency(1); |
|--------|----------------------------|--------------------------|
| 20 MHz | 1222 Hz                    | 1222 Hz                  |
| 16 MHz | 976 Hz                     | 976 Hz                   |
| 8 MHz  | 488 Hz                     | 7820 Hz                  |
| 4 MHz  | 976 Hz                     | 3910 Hz                  |
| 2 MHz  | 976 Hz                     | 1954 Hz                  |
| 1 MHz  | 2605 Hz                    | 2605 Hz                  |

**Comment by egilkv** [comment]
I obviously forgot to include the F_CPU compensation in analogWriteFrequency(), now done. 

8 MHz is a problem because there is no divider ratio that matches, so the default PWM frequency will be either 488 Hz or 1950 Hz. Which one do you prefer?

I looked at internal 1 MHz, but it seems it is not available in hardware. So I think the CPU is actually running at some much higher rate, and that the choice "1MHz internal" should be removed. Perhaps you can estimate the CPU speed by running a simple test loop the same number of times at different CPU speeds, and time it.

**Comment by MCUdude** [comment]
8 MHz is a problem because there is no divider ratio that matches, so the default PWM frequency will be either 488 Hz or 1950 Hz. Which one do you prefer?

1950 Hz is preferred. 

> I looked at internal 1 MHz, but it seems it is not available in hardware. So I think the CPU is actually running at some much higher rate, and that the choice "1MHz internal" should be removed. Perhaps you can estimate the CPU speed by running a simple test loop the same number of times at different CPU speeds, and time it.

So you believe that the actual clock is running faster than 1 MHz? I can always output the clock signal to a GPIO and read it with the oscilloscope.

**Comment by egilkv** [comment]
Correction on 1 MHz: It seems to me it was not supported in the software; the hardware seems to support it. I have submitted a small fix.

**Comment by MCUdude** [comment]
Exactly the same result for all clock except for 1 MHz, which is OK now.
Why is `analogWriteFrequency(1);` affecting the speed? I thought 1 kHz would be the default option?

| Clock  | //analogWriteFrequency(1); | analogWriteFrequency(1); |
|--------|----------------------------|--------------------------|
| 20 MHz | 1222 Hz                    | 1222 Hz                  |
| 16 MHz | 976 Hz                     | 976 Hz                   |
| 8 MHz  | 488 Hz                     | 7820 Hz                  |
| 4 MHz  | 976 Hz                     | 3910 Hz                  |
| 2 MHz  | 976 Hz                     | 1954 Hz                  |
| 1 MHz  | 976 Hz                     | 976 Hz                   |

**Comment by egilkv** [comment]
I believe I found the problem. Thanks for your patience!

**Comment by MCUdude** [comment]
Thank you! I'll continue testing tomorrow morning

**Comment by MCUdude** [comment]
Here's a more comprehensive test. So there's no way we can acheive higher PWM frequencies for lower clocks?

| Clock  | No analogWriteFrequency setting | analogWriteFrequency(1) | an..(4) | an..(8) | an..(16) | an..(32) | an..(64) |
|--------|---------------------------------|-------------------------|---------|---------|----------|----------|----------|
| 20 MHz | 1222 Hz                         | 1222 Hz                 | 4888 Hz | 9786 Hz | 19573 Hz | 39156 Hz | 78338 Hz |
| 16 MHz | 978 Hz                          | 978 Hz                  | 3913 Hz | 7827 Hz | 15655 Hz | 31319 Hz | 62628 Hz |
| 8 MHz  | 1956 Hz                         | 1956 Hz                 | 3913 Hz | 7827 Hz | 15655 Hz | 31319 Hz | 31319 Hz |
| 4 MHz  | 978 Hz                          | 978 Hz                  | 3913 Hz | 7827 Hz | 15655 Hz | 15655 Hz | 15655 Hz |
| 2 MHz  | 978 Hz                          | 978 Hz                  | 3913 Hz | 7827 Hz | 7827 Hz  | 7827 Hz  | 7827 Hz  |
| 1 MHz  | 978 Hz                          | 978 Hz                  | 3913 Hz | 3913 Hz | 3913 Hz  | 3913 Hz  | 3913 Hz  |

**Comment by MCUdude** [comment]
Why not use TCB2 for tone instead? It wouldn't make much of a difference of the 48-pin chips, but we prevent losing a PWM output pin on the 40-pin, 32-pin and 28 pin parts.

**Comment by egilkv** [comment]
> So there's no way we can acheive higher PWM frequencies for lower clocks?
No. At least if you want a PWM resolution of 8 bits. The highest frequency you can have is F_CPU/256, which for 1MHz is about 4kHz. For more, simply crank up the CPU.

**Comment by egilkv** [comment]
> Why not use TCB2 for tone instead? It wouldn't make much of a difference of the 48-pin chips, but we prevent losing a PWM output pin on the 40-pin, 32-pin and 28 pin parts.
tone() also cannot share the timer with micros(), and for  28 and 32 pins the sensible choice for the timer is TCB2.  The wifi has TCB3,  for timerhich is fine for compatibility. For the 48 pin we now have TCB2, which after more thinking I think is actually quite good. 

To be honest, I do not think loosing one PWM when using tone() is very much of an issue.

**Comment by MCUdude** [comment]
Oh, I totally forgot about micros(). Wery well, I think we're pretty much done! Do you agree?

**Comment by egilkv** [comment]
> Wery well, I think we're pretty much done! Do you agree?

Except for delayMicroseconds(), I guess. Which is ugly and kind of PITA. Is it possible for you to check the behaviour before?

**Comment by egilkv** [comment]
I did a very quick test, and found delayMicroseconds() was actually not that bad. Tried 16 and 4 MHz, 10, 100 and 1000 us. So maybe better to leave it as is. Even though there probably is a better way of implementing it using the new timer, it is not entirely trivial and I do not think I have time right now,

**Comment by MCUdude** [comment]
> I did a very quick test, and found delayMicroseconds() was actually not that bad.

Let's leave delayMicroseconds like it is for now. It has never really been driven by a timer either. Just look at the code to the other AVRs.

Thank you for your contributions, I really appreciate it! I will update the pinout diagrams accordingly. If you want new challenges fell free to look at the attachInterrupt implementation!

**Comment by egilkv** [comment]
> If you want new challenges fell free to look at the attachInterrupt implementation!

Yes, it is slow and uses a lot of RAM for the vector table. But if you want the flexibility that the user can individuallt assign an interrupt to each and every pin, I guess there is no way around that. The code can be optimized a bit, but it will only help so much. If you want the code to be much quicker and use much less RAM, you will need to restrict what is supported. (For instance you could have only six user defined interrupts, one for each port group, PA, PB etc. And have the mask of which bit in the group as an argument. But it would place a burden on the user to figure this out, and also the user would have to relate pin numbers to Px, which really seems non-Arduinesque. 

My guess is that it is possible to optimize the speed of the interrupt handler by, say, 30%, no more. Unless one starts with tricks like optimizing for special cases like when there happens to be max one interrupt defined per port, which would add to code size and complexity.

**Comment by MCUdude** [comment]
I understand. My initial worry was the overhead inside the ISR itself.

I rewroteISR by pointing directly to the PORT rather than figuring it out through an array. I haven't done a speed comparison, but I'm pretty sure it's a little faster.

```c
static void port_interrupt_handler(PORT_t* PORT, uint8_t port_num) {

  /* Copy flags */
  uint8_t int_flags = PORT->INTFLAGS;

  uint8_t bit_pos = PIN0_bp;
  uint8_t bit_mask = PIN0_bm;

  /* Iterate through flags */
  while(bit_pos <= PIN7_bp){

    /* Check if flag raised */
    if(int_flags & bit_mask){

    /* Get interrupt */
    uint8_t interrupt_num = port_num * 8 + bit_pos;

      /* Check if function defined */
      //if(intFunc[interrupt_num] != 0){ // This _is_ an ISR. Keep it as short as possible!

        /* Call function */
        intFunc[interrupt_num]();
      //}
    }
    bit_pos++;
    bit_mask = (bit_mask << 1); 
  }

  /* Clear flags that have been handled */
  PORT->INTFLAGS = int_flags;
}

#define IMPLEMENT_ISR(vect, port, port_num) \
ISR(vect) { \
  port_interrupt_handler(port, port_num);\
} \

IMPLEMENT_ISR(PORTA_PORT_vect, &PORTA, PA)
IMPLEMENT_ISR(PORTB_PORT_vect, &PORTB, PB)
IMPLEMENT_ISR(PORTC_PORT_vect, &PORTC, PC)
IMPLEMENT_ISR(PORTD_PORT_vect, &PORTD, PD)
IMPLEMENT_ISR(PORTE_PORT_vect, &PORTE, PE)
IMPLEMENT_ISR(PORTF_PORT_vect, &PORTF, PF)
```

**Comment by egilkv** [comment]
> I rewroteISR by pointing directly to the PORT rather than figuring it out through an array. I haven't done a speed comparison, but I'm pretty sure it's a little faster.

A bit faster, I would guess. You could avoid the loop altogether, that would save significant time and perhaps only add a bit more code size, something like:

```c
  int_flags = PORT->INTFLAGS;
  uint8_t interrupt_num0 = port_num * 8;
  if (int_flags & 0x01) intFunc[interrupt_num0]();
  if (int_flags & 0x02) intFunc[interrupt_num0+1]();
  if (int_flags & 0x04) intFunc[interrupt_num0+2]();
  if (int_flags & 0x08) intFunc[interrupt_num0+3]();
  if (int_flags & 0x10) intFunc[interrupt_num0+4]();
  if (int_flags & 0x20) intFunc[interrupt_num0+5]();
  if (int_flags & 0x40) intFunc[interrupt_num0+6]();
  if (int_flags & 0x80) intFunc[interrupt_num0+7]();
  PORT->INTFLAGS = int_flags;
```

**Comment by egilkv** [comment]
Under the assumption that you often only serve one interrupt, you could even add a binary search option here, so that you normally only execute 5 if-tests, which is a slight further improvement, but more code again:


```c
  int_flags = PORT->INTFLAGS;
  uint8_t interrupt_num0 = port_num * 8;
  if (int_flags & 0x0f) {
    if (int_flags & 0x03) {
      if (int_flags & 0x01) intFunc[interrupt_num0]();
      if (int_flags & 0x02) intFunc[interrupt_num0+1]();
    }
    if (int_flags & 0xc0) {
      if (int_flags & 0x04) intFunc[interrupt_num0+2]();
      if (int_flags & 0x08) intFunc[interrupt_num0+3]();
    }
  }
  if (int_flags & 0xf0) {
    if (int_flags & 0x30) {
      if (int_flags & 0x10) intFunc[interrupt_num0+4]();
      if (int_flags & 0x20) intFunc[interrupt_num0+5]();
    }
    if (int_flags & 0xc0) {
      if (int_flags & 0x40) intFunc[interrupt_num0+6]();
      if (int_flags & 0x80) intFunc[interrupt_num0+7]();
    }
  }
  PORT->INTFLAGS = int_flags;
```

**Comment by MCUdude** [comment]
It seems like the Arduino devs are working on another attachInterrupt implementation [here](https://github.com/arduino/ArduinoCore-megaavr/commit/ebd14ded5a31191fcb75b51fbfdcc276400fa41d). Not sure if this will be faster and/or less memory-hungry though.

**Pull request merged**
