### PR TITLE
[Logic] Separate CCL block instances

### PR DESCRIPTION
**Pull request by tgtakaoka**
This CL makes 4 CCL block instances in Logic object separated in Logic0 through Logic3 objects. Thus compiler/linker can optimize out unused block object from a sketch and reduce RAM consumption.

### CODE REVIEW

**Comment by MCUdude** [comment]
Thanks for the PR! Seems like a merge conflict has snuck in after I merged your previous PR

**Comment by MCUdude** [comment]
Now merged.

Thanks for your contribution. The library turned out quite elegant! When I first wrote it I was thinking about adding tiny0/tiny1 support too, but the physical location of logic inputs and output is not as consistent as on the mega0 series, and they are missing some registers. However, I think it should be solvable with some preprocessor magic.

I believe there is an error in the attiny1617/3217 datasheet because I can't find any traces of the CCL interrupt vectors or any of the CCL interrupt related registers in iotn1617/iotn3217.h. In the screenshot below you can also see that INT0CTRL has the same offset as LUT0CTRLA.

image

image

**Comment by tgtakaoka** [comment]
Thank you for merging the PR.

Regarding that both datasheet and header has no CCL interrupt related feature, it may be intentionally removed from tinyAVR series and differentiation between megaAVR series.

[ATtiny212/ATtiny412]
28. CCL
28.3 Function Description
28.3.2 Operation
28.3.2.7 Clock Source Settings
28.3.3 Events
28.3.4 Sleep Mode 

[megaAVR 0-series]
26. CCL
26.3 Functional Description
26.3.1 Operation
26.3.1.8 Clock Source Settings
26.3.2 Interrupts
26.3.3 Events
26.3.4 Sleep Mode

**Comment by tgtakaoka** [comment]
Hmm, https://github.com/MCUdude/MegaCoreX/pull/45/commits/d44f29d310faf27f1e453fb1da0d1f86a66b85c5 introduced extra lines to Logic.cpp..

`CustomLogic Logic;`

should be removed.

**Comment by tgtakaoka** [comment]
Created https://github.com/MCUdude/MegaCoreX/pull/46 to fix the issue.

**Comment by MCUdude** [comment]
> Regarding that both datasheet and header has no CCL interrupt related feature, it may be intentionally removed from tinyAVR series and differentiation between megaAVR series.

Yes, it seems like that's the intention. It also looks like some of the bits in the INSEL registers do different things. If you write 0x08 to LUTnCTRLB, it connects a USART on the megaAVR, but TCA0 on tinyAVR.

**Comment by MCUdude** [comment]
As a start, I was thinking that we could move all target specific stuff into the constructor. I started out by adding all pin definitions line this:

``` c++
// Object for logic block 0 (IOs connected to PORTA)
Logic Logic0(0, PORTA, PIN0_bm, PIN1_bm, PIN2_bm, PIN3_bm, PIN6_bm, CCL_SEQCTRL0, CCL_LUT0CTRLA, CCL_LUT0CTRLB, CCL_LUT0CTRLC, CCL_TRUTH0);

// Object for logic block 1 (IOs connected to PORTC)
Logic Logic1(1, PORTC, PIN0_bm, PIN1_bm, PIN2_bm, PIN3_bm, PIN6_bm, CCL_SEQCTRL0, CCL_LUT1CTRLA, CCL_LUT1CTRLB, CCL_LUT1CTRLC, CCL_TRUTH1);

// Object for logic block 2 (IOs connected to PORTD)
Logic Logic2(2, PORTD, PIN0_bm, PIN1_bm, PIN2_bm, PIN3_bm, PIN6_bm, CCL_SEQCTRL1, CCL_LUT2CTRLA, CCL_LUT2CTRLB, CCL_LUT2CTRLC, CCL_TRUTH2);

// Object for logic block 3 (IOs connected to PORTF)
Logic Logic3(3, PORTF, PIN0_bm, PIN1_bm, PIN2_bm, PIN3_bm, PIN6_bm, CCL_SEQCTRL1, CCL_LUT3CTRLA, CCL_LUT3CTRLB, CCL_LUT3CTRLC, CCL_TRUTH3);

Logic::Logic(
    const uint8_t block_number,
    PORT_t& port,
    const uint8_t in0_pin,
    const uint8_t in1_pin,
    const uint8_t in2_pin,
    const uint8_t out_pin,
    const uint8_t alt_out_pin,
    register8_t& seq_ctrl,
    register8_t& lut_ctrla,
    register8_t& lut_ctrlb,
    register8_t& lut_ctrlc,
    register8_t& truth)
    : BLOCK_NUMBER(block_number),
      PORT(port),
      IN0_PIN(in0_pin),
      IN1_PIN(in1_pin),
      IN2_PIN(in2_pin),
      OUT_PIN(out_pin),
      ALT_OUT_PIN(alt_out_pin),
      SEQCTRL(seq_ctrl),
      LUTCTRLA(lut_ctrla),
      LUTCTRLB(lut_ctrlb),
      LUTCTRLC(lut_ctrlc),
      TRUTH(truth),
      input0(in::masked),
      input1(in::masked),
      input2(in::masked),
      output(false),
      enable(false),
      truth(0x00),
      output_swap(out::no_swap),
      filter(filter::disable),
      sequencer(sequencer::disable)
{
}
```

But this increases the RAM usage compared to the version we have right now. How is this possible when IN0_PIN...IN2PIN, OUT_PIN and ALT_OUT_PIN is defined as `const uint8_t` in Logic.h?

**Comment by tgtakaoka** [comment]
I checked datasheets of ATtiny1607 and ATtiny3217 and realized that those have only 2 CCL blocks. Also those has different input/output mapping, even different port for alternate output :(.
I filed https://github.com/MCUdude/MegaCoreX/issues/47 for this.

I think that Logic library should have separate configuration data for CCL port/pin mapping other than Logic class which should be focused on configuring CCL settings.

I'll try prototype code and get back to you for your thought.

**Pull request merged**
